
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ReSCat
{

using System;
    using System.Collections.Generic;
    
public partial class MainTable
{

    public int Id { get; set; }

    public Nullable<int> Planned_Week { get; set; }

    public Nullable<int> Actual_Week { get; set; }

    public Nullable<double> Weight { get; set; }

    public string Order { get; set; }

    public string Client_Name { get; set; }

    public string Name { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<bool> IsFinished { get; set; }

}

}
